# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# pool:
#   vmImage: 'Ubuntu-16.04'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# - task: CMake@1
#   inputs:
#     cmakeArgs: '-DCOOLPROP_SHARED_LIBRARY'


jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: echo hello from macOS

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: echo hello from Windows

- job: MS_build
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: echo hello from Windows
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '-DCOOLPROP_SHARED_LIBRARY'
  - task: MSBuild@1
    inputs:
      solution: 'build/ALL_BUILD.vcxproj'

- job: Windows_build
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: echo hello from Windows
  - script: mkdir build
  - script: cd build && cmake .. -DCOOLPROP_SHARED_LIBRARY && cd ..
  - script: cd build && cmake --build .  && cd ..
